brew 'bash'
brew 'bash-completion'

tap 'thoughtbot/formulae'
tap 'homebrew/completions'

brew 'coreutils'
brew 'gnu-tar'
brew 'rbenv'
brew 'ruby-build'
brew 'exenv'
brew 'elixir-build'
brew 'erlang'
brew 'tig'
brew 'rcm'
brew 'sshrc'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'gnupg'
brew 'gpg-agent'
brew 'pinentry-mac'
