if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export ANDROID_HOME=/Users/litt/Library/Android/sdk
export ANDROID_SDK_ROOT=/Users/litt/Library/Android/sdk
